algoritmo "semnome"
// Função :
// Autor :
// Data : 17/04/2017
// Seção de Declarações 
var
valor:real
juros:real
porcentual:real
inicio
// Seção de Comandos 
escreva("digite o total de seu dinheiro: ")
leia(valor)
escreva("digite o o juros de redimento: ")
leia(porcentual)
juros <- valor*porcentual /100
escreval("seu valor com o redimento fixo após um mês é: ", valor+juros )

fimalgoritmo
