algoritmo "exercicio 5 ler duas variaveis e efutar troca dos valores "
// Função :
// Autor :
// Data : 01/04/2017
// Seção de Declarações 
var
a: real
b: real
troca: real
inicio
// Seção de Comandos 
escreva("digite um valor para A: ")
leia(a)
escreva("digite um valor para B: ")
leia(b)
troca <- a
a <- b
b <- troca
escreval("resultado da troca de valores: A ", a)

escreval("resultado da troca de valores: B ", b)

fimalgoritmo
